export type Language = 'vi' | 'en';

export const translations = {
  vi: {
    backofficeSystem: "Backoffice System",
    adminUser: "Admin User",
    logout: "Đăng xuất",
    common: "CHUNG",
    overview: "Tổng quan",
    myWork: "Việc của tôi",
    departments: "Phòng ban",
    employees: "Nhân viên",
    departmentsSection: "PHÒNG BAN",
    sales: "Sales",
    operations: "Operations",
    marketing: "Marketing",
    finance: "Finance",
    it: "IT",
    legal: "Legal",
    system: "HỆ THỐNG",
    requests: "Yêu cầu",
    approvals: "Phê duyệt",
    documents: "Tài liệu",
    reports: "Báo cáo",
    aiCoordinator: "AI Điều phối",
    settings: "Cài đặt",

    // Employee Management Page
    employeeList: "Danh sách nhân viên",
    addEmployee: "Thêm nhân viên",
    searchPlaceholder: "Tìm kiếm theo tên, email, SĐT...",
    branchAll: "Chi nhánh: Tất cả",
    branchHn: "Hà Nội",
    branchHcm: "Hồ Chí Minh",
    departmentAll: "Phòng ban: Tất cả",
    statusAll: "Trạng thái: Tất cả",
    statusActive: "Đang làm việc",
    statusInactive: "Nghỉ việc",
    statusPause: "Tạm nghỉ",
    filterBtn: "Bộ lọc",
    colIndex: "#",
    colEmployee: "Nhân viên",
    colEmpCode: "Mã nhân viên",
    colDepartment: "Phòng ban",
    colTitle: "Chức danh",
    colEmail: "Email",
    colPhone: "SĐT",
    colStatus: "Trạng thái",
    colActions: "Thao tác",

    // Add Employee Modal
    addNewEmployee: "Thêm nhân viên mới",
    cancel: "Hủy bỏ",
    saveEmployee: "Lưu nhân viên",
    fullNameLabel: "Họ và tên *",
    fullNamePlaceholder: "Nhập họ và tên",
    empCodeLabel: "Mã nhân viên *",
    emailLabel: "Email *",
    departmentLabel: "Phòng ban",
    selectDepartment: "Chọn phòng ban",
    titleLabel: "Chức danh",
    titlePlaceholder: "Nhập chức danh",

    // Account Security Page
    changePassword: "Thay đổi mật khẩu",
    twoFactorAuth: "Xác thực 2 lớp (2FA)",
    sessions: "Phiên đăng nhập",
    loginHistory: "Lịch sử đăng nhập",
    devices: "Thiết bị đã đăng nhập",
    updatePasswordDesc: "Vui lòng cập nhật mật khẩu mới để bảo vệ tài khoản của bạn.",
    currentPasswordLabel: "Mật khẩu hiện tại *",
    currentPasswordPlaceholder: "Nhập mật khẩu hiện tại",
    newPasswordLabel: "Mật khẩu mới *",
    newPasswordPlaceholder: "Nhập mật khẩu mới",
    confirmPasswordLabel: "Xác nhận mật khẩu mới *",
    confirmPasswordPlaceholder: "Nhập lại mật khẩu mới",
    passwordReq1: "Tối thiểu 8 ký tự",
    passwordReq2: "Bao gồm chữ hoa, chữ thường, số và ký tự đặc biệt",
    passwordReq3: "Không chứa khoảng trắng",
    updatePasswordBtn: "Cập nhật mật khẩu",
    featureInDev: "Tính năng đang được phát triển..."
  },
  en: {
    backofficeSystem: "Backoffice System",
    adminUser: "Admin User",
    logout: "Logout",
    common: "GENERAL",
    overview: "Overview",
    myWork: "My Work",
    departments: "Departments",
    employees: "Employees",
    departmentsSection: "DEPARTMENTS",
    sales: "Sales",
    operations: "Operations",
    marketing: "Marketing",
    finance: "Finance",
    it: "IT",
    legal: "Legal",
    system: "SYSTEM",
    requests: "Requests",
    approvals: "Approvals",
    documents: "Documents",
    reports: "Reports",
    aiCoordinator: "AI Coordinator",
    settings: "Settings",

    // Employee Management Page
    employeeList: "Employee List",
    addEmployee: "Add Employee",
    searchPlaceholder: "Search by name, email, phone...",
    branchAll: "Branch: All",
    branchHn: "Hanoi",
    branchHcm: "Ho Chi Minh",
    departmentAll: "Department: All",
    statusAll: "Status: All",
    statusActive: "Active",
    statusInactive: "Resigned",
    statusPause: "On Leave",
    filterBtn: "Filter",
    colIndex: "#",
    colEmployee: "Employee",
    colEmpCode: "Emp Code",
    colDepartment: "Department",
    colTitle: "Title",
    colEmail: "Email",
    colPhone: "Phone",
    colStatus: "Status",
    colActions: "Actions",

    // Add Employee Modal
    addNewEmployee: "Add New Employee",
    cancel: "Cancel",
    saveEmployee: "Save Employee",
    fullNameLabel: "Full Name *",
    fullNamePlaceholder: "Enter full name",
    empCodeLabel: "Employee Code *",
    emailLabel: "Email *",
    departmentLabel: "Department",
    selectDepartment: "Select department",
    titleLabel: "Job Title",
    titlePlaceholder: "Enter job title",

    // Account Security Page
    changePassword: "Change Password",
    twoFactorAuth: "Two-Factor Auth (2FA)",
    sessions: "Login Sessions",
    loginHistory: "Login History",
    devices: "Logged-in Devices",
    updatePasswordDesc: "Please update your password to protect your account.",
    currentPasswordLabel: "Current Password *",
    currentPasswordPlaceholder: "Enter current password",
    newPasswordLabel: "New Password *",
    newPasswordPlaceholder: "Enter new password",
    confirmPasswordLabel: "Confirm New Password *",
    confirmPasswordPlaceholder: "Re-enter new password",
    passwordReq1: "Minimum 8 characters",
    passwordReq2: "Includes uppercase, lowercase, number, and special character",
    passwordReq3: "No spaces allowed",
    updatePasswordBtn: "Update Password",
    featureInDev: "Feature in development..."
  }
};

export type TranslationKey = keyof typeof translations.vi;
