#!/bin/bash
# Installs or updates bo-prod-ops, AS ROOT, from a reviewed commit of main. The
# ONLY way these files change: a release never touches them. Idempotent - a
# second run with the same sources changes nothing and says so. Runbook: README.md.
#
#   bash install.sh <40-hex commit these files came from> [ops public key file]
#
# With a public key it also (re)writes the bo-ops account's authorized_keys: that
# key, restricted, forced to run `sudo -n bo-prod-ops "<one argument>"` and
# nothing else. Generated here because its quoting is too easy to get wrong by hand.
#
# Order is deliberate: every check and the sudoers validation happen BEFORE the
# first write, and the sudo rule (which pins the wrapper's sha256) is replaced
# LAST - in between, sudo refuses the new wrapper, which fails closed.
set -euo pipefail -o noglob
export PATH=/usr/sbin:/usr/bin:/sbin:/bin LC_ALL=C
umask 022

readonly OPS_USER=bo-ops
readonly BIN=/usr/local/sbin/bo-prod-ops LIB=/usr/local/lib/bo-prod-ops SUDOERS=/etc/sudoers.d/bo-prod-ops
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly HERE

die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
owner_mode() { stat -c '%u:%g %a' "$1"; }

(( EUID == 0 )) || die "run as root"
[[ $# -ge 1 && $# -le 2 && "$1" =~ ^[0-9a-f]{40}$ ]] || die "usage: install.sh <40-hex commit these files came from> [ops public key file]"
readonly SOURCE_COMMIT="$1" PUBKEY="${2-}"
for tool in visudo sudo docker sha256sum stat install cmp mktemp awk; do
  command -v "$tool" >/dev/null || die "$tool is not installed"
done
id -u "$OPS_USER" >/dev/null 2>&1 || die "the $OPS_USER account does not exist yet - create it first (README.md)"
# Never add a rule to a sudo configuration that is already invalid: the final
# check could then not tell our mistake from one that was already there.
visudo -c >/dev/null || die "sudo's configuration is already invalid (visudo -c above) - fix that first; nothing was installed"
OPS_HOME="$(awk -F: -v u="$OPS_USER" '$1 == u { print $6 }' /etc/passwd)"
readonly OPS_HOME
[[ "$OPS_HOME" == /* && -d "$OPS_HOME" ]] || die "$OPS_USER has no home directory"

# Nothing we write into may be writable by anyone but root.
for dir in / /usr /usr/local /usr/local/sbin /usr/local/lib /etc /etc/sudoers.d; do
  [[ -d "$dir" ]] || die "$dir does not exist"
  read -r own mode <<< "$(owner_mode "$dir")"
  [[ "$own" == 0:* && $(( 8#$mode & 8#022 )) == 0 ]] || die "$dir is not root-owned or is writable by others ($own $mode)"
done
# An existing target that is not root's means somebody else could have written
# it. Stop and find out why; do not paper over it by replacing the file.
targets=("$BIN" "$LIB" "$LIB/trip-confirmed-audit.sql" "$LIB/SOURCE" "$SUDOERS")
[[ -z "$PUBKEY" ]] || targets+=("$OPS_HOME/.ssh/authorized_keys")
for target in "${targets[@]}"; do
  [[ ! -e "$target" ]] || [[ "$(owner_mode "$target")" == 0:0* ]] || die "$target exists and is not owned by root:root - investigate"
done

# The sources must agree with each other before anything is installed.
pin="$(sed -n 's/^readonly AUDIT_SQL_SHA256=//p' "$HERE/bo-prod-ops")"
[[ "$pin" =~ ^[0-9a-f]{64}$ ]] || die "the wrapper carries no audit SQL checksum"
[[ "$(sha256sum < "$HERE/trip-confirmed-audit.sql")" == "$pin  -" ]] || die "trip-confirmed-audit.sql does not match the wrapper's pin"
bash -n "$HERE/bo-prod-ops" || die "the wrapper does not parse"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
digest="$(sha256sum < "$HERE/bo-prod-ops" | cut -d' ' -f1)"
# One argument each, exactly - never a wildcard. The digest makes sudo refuse a
# wrapper that is not byte-identical to this one.
cat > "$work/sudoers" <<EOF
# bo-prod-ops $SOURCE_COMMIT - generated by ops/prod-ops/install.sh, do not edit
Cmnd_Alias BO_PROD_OPS = sha256:$digest $BIN trip-confirmed-audit, \\
                         sha256:$digest $BIN trip-confirmed-normalize
Defaults!BO_PROD_OPS env_reset, secure_path="/usr/sbin:/usr/bin:/sbin:/bin"
$OPS_USER ALL=(root) NOPASSWD: BO_PROD_OPS
EOF
visudo -cf "$work/sudoers" >/dev/null || die "the generated sudoers rule does not parse - nothing was installed"
printf '%s\n' "$SOURCE_COMMIT" > "$work/SOURCE"
if [[ -n "$PUBKEY" ]]; then
  key="$(tr -d '\r' < "$PUBKEY")"
  [[ "$key" =~ ^(ssh-ed25519|ecdsa-sha2-nistp256|ssh-rsa)\ [A-Za-z0-9+/]+=*(\ [A-Za-z0-9@._-]*)?$ ]] \
    || die "$PUBKEY is not exactly one SSH public key line"
  # The shell sshd starts expands "$SSH_ORIGINAL_COMMAND" as ONE word: whatever the
  # client sends becomes a single argument, which sudoers then matches exactly.
  # shellcheck disable=SC2016 # $SSH_ORIGINAL_COMMAND is for the remote shell, not this one
  printf 'restrict,command="sudo -n %s \\"$SSH_ORIGINAL_COMMAND\\"" %s\n' "$BIN" "$key" > "$work/authorized_keys"
fi

# Atomic and idempotent: a temp file in the SAME directory, then rename. The
# temp name starts with "." so sudo never reads a half-written sudoers file.
place() {
  local src="$1" dst="$2" mode="$3" tmp
  if [[ -f "$dst" ]] && cmp -s "$src" "$dst" && [[ "$(owner_mode "$dst")" == "0:0 $mode" ]]; then
    printf 'unchanged  %s\n' "$dst"; return 0
  fi
  tmp="$(mktemp "$(dirname "$dst")/.bo-prod-ops.XXXXXX")"
  install -o root -g root -m "$mode" "$src" "$tmp"
  mv -f "$tmp" "$dst"
  printf 'installed  %s\n' "$dst"
}
install -d -o root -g root -m 755 "$LIB"
place "$HERE/trip-confirmed-audit.sql" "$LIB/trip-confirmed-audit.sql" 644
place "$work/SOURCE" "$LIB/SOURCE" 644
place "$HERE/bo-prod-ops" "$BIN" 755
if [[ -n "$PUBKEY" ]]; then
  install -d -o root -g root -m 755 "$OPS_HOME/.ssh"
  place "$work/authorized_keys" "$OPS_HOME/.ssh/authorized_keys" 644
fi
place "$work/sudoers" "$SUDOERS" 440
visudo -c >/dev/null || die "sudo's configuration no longer parses - fix $SUDOERS NOW, before logging out"

printf '\n%s\n' "bo-prod-ops installed from $SOURCE_COMMIT"
sha256sum "$BIN" "$LIB/trip-confirmed-audit.sql" "$SUDOERS"
stat -c '%U:%G %a  %n' "$BIN" "$LIB" "$LIB/trip-confirmed-audit.sql" "$LIB/SOURCE" "$SUDOERS"
[[ ! -e "$OPS_HOME/.ssh/authorized_keys" ]] || stat -c '%U:%G %a  %n' "$OPS_HOME/.ssh" "$OPS_HOME/.ssh/authorized_keys"
sudo -l -U "$OPS_USER"
