-- 0030_shared_trip_locations.sql — PROJECT-OWNED (Hoàng Long dispatch).
--
-- A place can belong to nobody, and that is the point.
--
-- 0022 made every location a customer's: `customer_id NOT NULL`, one door in
-- (the customer's own row), no global list anywhere. That was right for a
-- customer's WAREHOUSE. It is wrong for Cảng Cát Lái, for ICD Phước Long, for
-- a hired yard — the places dispatch types over and over under a different
-- customer every week, each copy its own row, each copy located again.
--
-- ★ NULL MEANS SHARED. Not "unknown", not "not yet filed": a location with no
-- `customer_id` is one the whole company uses, entered once. A location WITH
-- one is unchanged in every respect — same routes, same rules, same screen.
-- Two populations in one table because they are the same thing with the same
-- columns, read by the same queries, snapshotted onto a trip the same way.
--
-- ★ THE SECOND UNIQUE INDEX IS NOT OPTIONAL. 0022's index is
-- `(customer_id, name_key) WHERE status = 'active'`, and PostgreSQL holds every
-- NULL distinct from every other NULL — so under a nullable `customer_id` that
-- index permits "Cảng Cát Lái" an unlimited number of times. The name rule the
-- catalogue is built on would have quietly stopped applying to exactly the rows
-- this file exists to create. The partial index below is where the rule lives
-- for them.
--
-- ★ THREE ADMINISTRATIVE LEVELS, AND VIETNAM CURRENTLY HAS TWO. READ ON.
--
-- From 1 July 2025 local government is two-tier: 34 tỉnh/thành, then 3,321
-- xã/phường/đặc khu, with quận/huyện ABOLISHED. These columns record the
-- PRE-reform hierarchy anyway — 63 provinces, districts, old wards — and that
-- is a decision, not an oversight.
--
-- The three are DESCRIPTIVE: nothing operational reads them. A trip snapshots
-- its own `address` (0022) and the geofence measures coordinates (0019). They
-- exist so a person can find a row in a list, and the people reading that list
-- — along with the customer contracts it is reconciled against — still say
-- "Quận 7" and "Bình Dương". The old hierarchy is also self-consistent, which
-- a mix of new provinces and old districts could never be.
--
-- ⚠ SO A ROW WRITTEN TODAY MAY NAME A PROVINCE THAT NO LONGER EXISTS. That is
-- the accepted cost. Moving to the current structure means pointing
-- `VN_ADMIN_API_URL` at the two-tier feed and stopping writing `district*`;
-- the columns would stay for the rows that already carry one.
--
-- ★ THE CODE IS THE IDENTITY, THE NAME IS THE LABEL. A ward can be renamed —
-- 2025 renamed thousands of them — and a row that stored only the name would
-- then hold a name that matches nothing. The state-issued code survives that,
-- so it is what identifies the unit; the name is stored beside it so a list
-- reads without calling anybody, and is refreshed from the code when it moves.
--
-- Nullable, no backfill. Every existing row keeps NULL and that is the TARGET
-- state, not unfinished work: nothing here knows where those rows are, and a
-- migration that guessed from the address text would be inventing a fact
-- somebody would later rely on. Cf. 0013 and `ownership`.
--
-- ⚠ AND THEY ARE DESCRIPTIVE, NOT OPERATIONAL. The trip snapshots `address`
-- (0022) and the geofence measures coordinates (0019). Neither reads these.
-- They exist so a human can find a place in a list, and a NULL in one of them
-- means "not recorded", never "outside Vietnam".

-- ------------------------------------------------ customer_id: now optional ----

ALTER TABLE trip_locations
  ALTER COLUMN customer_id DROP NOT NULL;

-- ------------------------------------ tỉnh/thành · quận/huyện · phường/xã ----

ALTER TABLE trip_locations
  ADD COLUMN IF NOT EXISTS province_code TEXT,
  ADD COLUMN IF NOT EXISTS province      TEXT,
  ADD COLUMN IF NOT EXISTS district_code TEXT,
  ADD COLUMN IF NOT EXISTS district      TEXT,
  ADD COLUMN IF NOT EXISTS ward_code     TEXT,
  ADD COLUMN IF NOT EXISTS ward          TEXT;

-- ------------------------------------------------ one shared name, in force ----
--
-- The mirror of `uq_trip_location_name` for the rows that index cannot see.
-- Same normalisation (`name_key` is generated by 0022), same "among ACTIVE rows
-- only" rule, so a shared place can close and reopen under its own name just as
-- a customer's can.

CREATE UNIQUE INDEX IF NOT EXISTS uq_trip_location_shared_name
  ON trip_locations (name_key)
  WHERE status = 'active' AND customer_id IS NULL;

-- The one read the new screen makes: every place, shared first. 0022's
-- `idx_trip_location_customer` serves the per-customer read and cannot serve
-- this one — it leads on `customer_id`, which this ordering puts last.
CREATE INDEX IF NOT EXISTS idx_trip_location_catalogue
  ON trip_locations (status, name);
